import { Transaction, Wallet, Category, TransactionType, User, Role, SavingsGoal } from './types';

export const initialWallets: Wallet[] = [
    { id: '1', name: { en: 'Cash', vi: 'Tiền mặt' }, currency: 'VND' },
    { id: '2', name: { en: 'Vietcombank', vi: 'Vietcombank' }, currency: 'VND' },
    { id: '3', name: { en: 'PayPal', vi: 'PayPal' }, currency: 'USD' },
];

export const initialCategories: Category[] = [
    // Expenses
    { id: 'cat-1', name: { en: 'Food & Dining', vi: 'Ăn uống' }, type: TransactionType.EXPENSE, icon: 'fast-food-outline' },
    { id: 'cat-2', name: { en: 'Transportation', vi: 'Di chuyển' }, type: TransactionType.EXPENSE, icon: 'bus-outline' },
    { id: 'cat-3', name: { en: 'Housing', vi: 'Nhà ở' }, type: TransactionType.EXPENSE, icon: 'home-outline' },
    { id: 'cat-4', name: { en: 'Shopping', vi: 'Mua sắm' }, type: TransactionType.EXPENSE, icon: 'cart-outline' },
    { id: 'cat-5', name: { en: 'Entertainment', vi: 'Giải trí' }, type: TransactionType.EXPENSE, icon: 'film-outline' },
    { id: 'cat-6', name: { en: 'Health & Fitness', vi: 'Sức khỏe' }, type: TransactionType.EXPENSE, icon: 'fitness-outline' },
    { id: 'cat-7', name: { en: 'Utilities', vi: 'Tiện ích' }, type: TransactionType.EXPENSE, icon: 'water-outline' },
    { id: 'cat-8', name: { en: 'Education', vi: 'Giáo dục' }, type: TransactionType.EXPENSE, icon: 'school-outline' },
    { id: 'cat-9', name: { en: 'Gifts & Donations', vi: 'Quà tặng & Quyên góp' }, type: TransactionType.EXPENSE, icon: 'gift-outline' },
    { id: 'cat-10', name: { en: 'Groceries', vi: 'Tạp hóa' }, type: TransactionType.EXPENSE, icon: 'basket-outline' },

    // Incomes
    { id: 'cat-11', name: { en: 'Salary', vi: 'Lương' }, type: TransactionType.INCOME, icon: 'cash-outline' },
    { id: 'cat-12', name: { en: 'Freelance', vi: 'Làm tự do' }, type: TransactionType.INCOME, icon: 'briefcase-outline' },
    { id: 'cat-13', name: { en: 'Investment', vi: 'Đầu tư' }, type: TransactionType.INCOME, icon: 'analytics-outline' },
    { id: 'cat-14', name: { en: 'Bonus', vi: 'Thưởng' }, type: TransactionType.INCOME, icon: 'star-outline' },
];

export const initialUsers: User[] = [
    { id: 'user-1', name: 'Alice', email: 'alice@example.com', role: Role.USER, status: 'active', avatarUrl: 'https://i.pravatar.cc/150?u=alice@example.com' },
    { id: 'user-2', name: 'Bob', email: 'bob@example.com', role: Role.USER, status: 'active', avatarUrl: 'https://i.pravatar.cc/150?u=bob@example.com' },
    { id: 'user-3', name: 'Charlie', email: 'charlie@example.com', role: Role.USER, status: 'locked', avatarUrl: 'https://i.pravatar.cc/150?u=charlie@example.com' },
    { id: 'user-4', name: 'Demo User', email: 'demo@example.com', role: Role.ADMIN, status: 'active', avatarUrl: 'https://i.pravatar.cc/150?u=demo@example.com' },
];

export const initialSavingsGoals: SavingsGoal[] = [
    { id: 'goal-1', name: 'iPhone 15 Pro', targetAmount: 30000000, currentAmount: 7500000, imageUrl: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692845699462' },
    { id: 'goal-2', name: 'Du lịch Nhật Bản', targetAmount: 50000000, currentAmount: 40000000, imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=2070&auto=format&fit=crop' },
];


const today = new Date();
const formatDate = (date: Date) => date.toISOString().split('T')[0];

export const initialTransactions: Transaction[] = [
    { id: 't-1', walletId: '2', categoryId: 'cat-11', type: TransactionType.INCOME, amount: 25000000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 1)), description: 'Lương tháng' },
    { id: 't-2', walletId: '1', categoryId: 'cat-1', type: TransactionType.EXPENSE, amount: 150000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 2)), description: 'Ăn trưa với đồng nghiệp' },
    { id: 't-3', walletId: '2', categoryId: 'cat-7', type: TransactionType.EXPENSE, amount: 1200000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 5)), description: 'Hóa đơn tiền điện' },
    { id: 't-4', walletId: '1', categoryId: 'cat-10', type: TransactionType.EXPENSE, amount: 850000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 6)), description: 'Đi siêu thị hàng tuần' },
    { id: 't-5', walletId: '1', categoryId: 'cat-2', type: TransactionType.EXPENSE, amount: 50000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 7)), description: 'Grab bike đi làm' },
    { id: 't-6', walletId: '2', categoryId: 'cat-4', type: TransactionType.EXPENSE, amount: 2500000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 10)), description: 'Giày chạy bộ mới' },
    { id: 't-7', walletId: '3', categoryId: 'cat-12', type: TransactionType.INCOME, amount: 5000000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 12)), description: 'Thanh toán dự án thiết kế web' },
    { id: 't-8', walletId: '1', categoryId: 'cat-5', type: TransactionType.EXPENSE, amount: 300000, date: formatDate(new Date(today.getFullYear(), today.getMonth(), 14)), description: 'Vé xem phim' },
];


export const locales = {
    en: {
        appTitle: 'AI Expense Manager',
        totalIncome: 'Total Income',
        totalExpense: 'Total Expense',
        balance: 'Balance',
        addTransaction: 'Add Transaction',
        spendingByCategory: 'Spending by Category',
        incomeVsExpense: 'Income vs Expense',
        recentTransactions: 'Recent Transactions',
        expense: 'Expense',
        income: 'Income',
        amount: 'Amount',
        description: 'Description',
        category: 'Category',
        wallet: 'Wallet',
        date: 'Date',
        selectCategory: 'Select a category',
        selectWallet: 'Select a wallet',
        add: 'Add',
        aiSuggesting: 'AI thinking...',
        formError: 'Please fill out all required fields.',
        noTransactions: 'No transactions yet.',
        noExpenseData: 'No expense data to display.',
        noTrendData: 'No data for trend chart.',
        role: 'Role',
        user: 'User',
        admin: 'Admin',
        language: 'Language',
        english: 'English',
        vietnamese: 'Vietnamese',
        descriptionPlaceholder: 'e.g., Coffee with friends',
        // Admin Panel
        adminPanel: 'Admin Panel',
        userManagement: 'User Management',
        categoryManagement: 'Category Management',
        allTransactions: 'All Transactions',
        name: 'Name',
        email: 'Email',
        status: 'Status',
        actions: 'Actions',
        active: 'Active',
        locked: 'Locked',
        lock: 'Lock',
        unlock: 'Unlock',
        categoryName: 'Category Name',
        type: 'Type',
        icon: 'Icon',
        addCategory: 'Add Category',
        editCategory: 'Edit Category',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        editTransaction: 'Edit Transaction',
        addNewTransaction: 'Add New Transaction',
        reports: 'Reports',
        systemFinancialSummary: 'System Financial Summary',
        totalTransactionsCount: 'Total Transactions',
        // Budget Planner
        budgetPlanner: 'Budget Planner',
        addPlannedExpense: 'Add Planned Expense',
        plannedExpenses: 'Planned Expenses',
        noPlannedExpenses: 'No planned expenses yet.',
        convertToTransaction: 'Convert to Transaction',
        plannedAmount: 'Planned Amount',
        // Savings Goals
        savingsGoals: 'Savings Goals',
        addGoal: 'Add Goal',
        goalName: 'Goal Name',
        targetAmount: 'Target Amount',
        currentAmount: 'Current Amount',
        addContribution: 'Add Contribution',
        contributionAmount: 'Contribution Amount',
        noSavingsGoals: 'No savings goals yet. Add one!',
        of: 'of',
        // Profile
        viewProfile: 'View Profile',
        editProfile: 'Edit Profile',
        logout: 'Logout',
        changeAvatar: 'Change Avatar',
        saveChanges: 'Save Changes',

    },
    vi: {
        appTitle: 'Trình quản lý chi tiêu AI',
        totalIncome: 'Tổng thu nhập',
        totalExpense: 'Tổng chi phí',
        balance: 'Số dư',
        addTransaction: 'Thêm giao dịch',
        spendingByCategory: 'Chi tiêu theo danh mục',
        incomeVsExpense: 'Thu nhập và Chi phí',
        recentTransactions: 'Giao dịch gần đây',
        expense: 'Chi phí',
        income: 'Thu nhập',
        amount: 'Số tiền',
        description: 'Mô tả',
        category: 'Danh mục',
        wallet: 'Ví tiền',
        date: 'Ngày',
        selectCategory: 'Chọn một danh mục',
        selectWallet: 'Chọn một ví',
        add: 'Thêm',
        aiSuggesting: 'AI đang nghĩ...',
        formError: 'Vui lòng điền vào tất cả các trường bắt buộc.',
        noTransactions: 'Chưa có giao dịch nào.',
        noExpenseData: 'Không có dữ liệu chi phí để hiển thị.',
        noTrendData: 'Không có dữ liệu cho biểu đồ xu hướng.',
        role: 'Vai trò',
        user: 'Người dùng',
        admin: 'Quản trị viên',
        language: 'Ngôn ngữ',
        english: 'Tiếng Anh',
        vietnamese: 'Tiếng Việt',
        descriptionPlaceholder: 'ví dụ: Cà phê với bạn bè',
        // Admin Panel
        adminPanel: 'Bảng điều khiển Admin',
        userManagement: 'Quản lý người dùng',
        categoryManagement: 'Quản lý danh mục',
        allTransactions: 'Tất cả giao dịch',
        name: 'Tên',
        email: 'Email',
        status: 'Trạng thái',
        actions: 'Hành động',
        active: 'Hoạt động',
        locked: 'Bị khóa',
        lock: 'Khóa',
        unlock: 'Mở khóa',
        categoryName: 'Tên danh mục',
        type: 'Loại',
        icon: 'Biểu tượng',
        addCategory: 'Thêm danh mục',
        editCategory: 'Sửa danh mục',
        save: 'Lưu',
        cancel: 'Hủy',
        delete: 'Xóa',
        edit: 'Sửa',
        editTransaction: 'Sửa Giao dịch',
        addNewTransaction: 'Thêm Giao dịch Mới',
        reports: 'Báo cáo',
        systemFinancialSummary: 'Tóm tắt Tài chính Hệ thống',
        totalTransactionsCount: 'Tổng số Giao dịch',
        // Budget Planner
        budgetPlanner: 'Hoạch định Ngân sách',
        addPlannedExpense: 'Thêm chi tiêu dự kiến',
        plannedExpenses: 'Các khoản chi dự kiến',

        noPlannedExpenses: 'Chưa có khoản chi dự kiến nào.',
        convertToTransaction: 'Chuyển thành Giao dịch',
        plannedAmount: 'Số tiền dự kiến',
        // Savings Goals
        savingsGoals: 'Mục tiêu Tiết kiệm',
        addGoal: 'Thêm Mục tiêu',
        goalName: 'Tên mục tiêu',
        targetAmount: 'Số tiền mục tiêu',
        currentAmount: 'Số tiền hiện tại',
        addContribution: 'Thêm Tiền',
        contributionAmount: 'Số tiền thêm vào',
        noSavingsGoals: 'Chưa có mục tiêu nào. Hãy thêm một mục tiêu!',
        of: 'của',
        // Profile
        viewProfile: 'Xem Hồ sơ',
        editProfile: 'Sửa Hồ sơ',
        logout: 'Đăng xuất',
        changeAvatar: 'Đổi ảnh đại diện',
        saveChanges: 'Lưu thay đổi',
    }
};